openapi: '3.0.0'
info:
  version: 1.0.0
  title: Monerochan Merchant RPC
  description: An API to easily accept payments in Monero
servers:
  - url: /v1
paths:
  /wallet/create:
    post:
      description:
        test
      summary: Subscribe to a webhook
      operationId: create
      x-eov-operation-handler: routes/wallet/create
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletCreate'
            examples:
              Testnet:
                value:
                  networkType: testnet
              Stagenet:
                value:
                  networkType: stagenet
      responses:
        '201':
          description: Webhook created
  /ping:
    get:
      description: 
        ping then pong!
      operationId: ping
      x-eov-operation-handler: routes/ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
components:
  schemas:
    WalletCreate:
      type: object
      properties:
        networkType:
          type: string
          enum: 
            - stagenet
            - mainnet
            - testnet
          default: mainnet