openapi: '3.0.0'
info:
  version: 1.0.0
  title: Monerochan Merchant RPC
  description: An API to easily accept payments in Monero
servers:
  - url: /v1
paths:
  /ping:
    get:
      description: 
        ping then pong!
      operationId: ping
      x-eov-operation-handler: routes/ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong