openapi: '3.0.0'
info:
  version: 1.0.0
  title: Monerochan Merchant RPC
  description: An API to easily accept payments in Monero
servers:
  - url: /v1
paths:
  /wallet/initialize:
    post:
      description: |
        call this endpoint to create the wallet file from primary address and viewkey. \
        This is the first endpoint you need to call. Afterwards you can call the /wallet/sync endpoint. 
      summary: create the wallet file from primary address and viewkey
      operationId: initialize
      x-eov-operation-handler: routes/wallet/initialize 
      tags:
       - startup tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletInitialize'
            examples:
              Testnet:
                value:
                  path: ./monerochans_testnet_stash
                  networkType: testnet
                  primaryAddress: 9uJ5JRXP3BQAGW1nHK9KzVHUifBfCAHnJKRnZ45ebYcQJrt2wprNgYoGWJvPrCW6nSiBAzmeSAGBGjM5kt2mRb3g98JJetV
                  privateViewKey: d99cca1f6794a0a856cde057421702482b8d56e36f31a939239f97e9f5a32b0d
                  restoreHeight: 0
              Stagenet:
                value:
                  path: ./monerochans_stagenet_stash
                  networkType: stagenet
                  primaryAddress: 55Py9fSwyEeQX1CydtFfPk96uHEFxSxvD9AYBy7dwnYt9cXqKDjix9rS9AWZ5GnH4B1Z7yHr3B2UH2updNw5ZNJEEnv87H1
                  privateViewKey: 1195868d30373aa9d92c1a21514de97670bcd360c209a409ea3234174892770e
                  restoreHeight: 957038
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: unexpected error
  /wallet/sync:
    post:
      description: |
        call this endpoint to start syncing the wallet after the wallet file was created. \
        This is the second endpoint you need to call after creating the wallet file with /wallet/initialize. \
        Afterwards you can call the accept payments & check api health endpoints. Or shut things down orderly with the shutdown tasks.
      summary: start syncing the wallet after the wallet file was created.
      operationId: sync
      x-eov-operation-handler: routes/wallet/sync 
      tags:
       - startup tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletSync'
            examples:
              Testnet:
                value:
                  path: ./monerochans_testnet_stash
                  networkType: testnet
                  serverUri: http://localhost:28081

              Stagenet:
                value:
                  path: ./monerochans_stagenet_stash
                  networkType: stagenet
                  serverUri: http://stagenet.xmr-tw.org:38081

      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessResponse'
        '500':
          description: unexpected error
  /wallets/status:
    get:
      description: |
        call this endpoint to get the syncing status of the currently opened wallets. \
        this endpoint can also be used check general api health (if the monerochan merchant api is still running).
      operationId: status
      x-eov-operation-handler: routes/wallets/status
      tags:
       - accept payments & check api health
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WalletStatusResponse'
        '500':
          description: unexpected error
components:
  schemas:
    WalletInitialize:
      type: object
      properties:
        path:
          type: string
        networkType:
          type: string
          enum: 
            - stagenet
            - mainnet
            - testnet
          default: mainnet
        primaryAddress:
          type: string
        privateViewKey:
          type: string
        restoreHeight:
          type: integer
      required:
        - path
        - primaryAddress
        - privateViewKey
        - restoreHeight
    WalletSync:
      type: object
      properties:
        path:
          type: string
        networkType:
          type: string
          enum: 
            - stagenet
            - mainnet
            - testnet
          default: mainnet
        serverUri:
          type: string
      required:
        - path
        - serverUri
    SuccessResponse:
      type: object
      properties:
        message:
          type: string
    WalletStatusResponse:
      type: array
      items:
        type: object
        properties:
          path:
            type: string
          status:
            type: string
            enum:
              - synching
              - not synching
        required:
          - status
          - path
      
tags:
  - name: startup tasks
    description: initialize & reopen & sync
  - name: accept payments & check api health
  - name: shutdown tasks 