openapi: '3.0.0'
info:
  version: 1.0.0
  title: Monerochan Merchant RPC
  description: An API to easily accept payments in Monero
servers:
  - url: /v1
paths:
  /wallet/initialize:
    post:
      description:
        test
      summary: Subscribe to a webhook
      operationId: initialize
      x-eov-operation-handler: routes/wallet/initialize 
      tags:
       - startup tasks
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/WalletInitialize'
            examples:
              Stagenet:
                value:
                  path: ./monerochans_stash
                  networkType: stagenet
                  primaryAddress: 55Py9fSwyEeQX1CydtFfPk96uHEFxSxvD9AYBy7dwnYt9cXqKDjix9rS9AWZ5GnH4B1Z7yHr3B2UH2updNw5ZNJEEnv87H1
                  privateViewKey: 1195868d30373aa9d92c1a21514de97670bcd360c209a409ea3234174892770e
                  restoreHeight: 957038
      responses:
        '200':
          description: Webhook created
  /ping:
    get:
      description: 
        ping then pong!
      operationId: ping
      x-eov-operation-handler: routes/ping
      responses:
        '200':
          description: OK
          content:
            text/plain:
              schema:
                type: string
                example: pong
components:
  schemas:
    WalletInitialize:
      type: object
      properties:
        path:
          type: string
        networkType:
          type: string
          enum: 
            - stagenet
            - mainnet
            - testnet
          default: mainnet
        primaryAddress:
          type: string
        privateViewKey:
          type: string
        restoreHeight:
          type: integer
      required:
        - path
        - primaryAddress
        - privateViewKey
        - restoreHeight
tags:
  - name: startup tasks
    description: initialize & reopen & sync
  - name: accept payments